create database projetowebii;
use projetowebii;
CREATE TABLE Papel (IdPapel int(11) NOT NULL AUTO_INCREMENT, Descricao varchar(50) NOT NULL, PRIMARY KEY (IdPapel));
CREATE TABLE Horario (IdHorario tinyint NOT NULL AUTO_INCREMENT, Horario time NOT NULL UNIQUE, PRIMARY KEY (IdHorario));
CREATE TABLE Escala (IdEscala int(11) NOT NULL AUTO_INCREMENT, IdPessoa int(11) NOT NULL, IdHorarioInicio tinyint NOT NULL, IdHorarioFim tinyint NOT NULL, PRIMARY KEY (IdEscala));
CREATE TABLE Funcionario (IdPessoa int(11) NOT NULL, IdPapel int(11) NOT NULL, PRIMARY KEY (IdPessoa));
CREATE TABLE StatusReserva (IdStatusReserva tinyint NOT NULL AUTO_INCREMENT, Descricao varchar(50) NOT NULL, PRIMARY KEY (IdStatusReserva));
CREATE TABLE StatusApartamento (IdStatusApartamento tinyint NOT NULL AUTO_INCREMENT, Descricao varchar(50) NOT NULL, PRIMARY KEY (IdStatusApartamento));
CREATE TABLE ApartamentoReserva (IdApartamento int(11) NOT NULL, IdReserva int(11) NOT NULL, PRIMARY KEY (IdApartamento, IdReserva));
CREATE TABLE Apartamento (IdApartamento int(11) NOT NULL AUTO_INCREMENT, Descricao int(11), NumeroQuartos int(11), IdStatusApartamento tinyint NOT NULL, PRIMARY KEY (IdApartamento));
CREATE TABLE Cliente (IdPessoa int(11) NOT NULL, PRIMARY KEY (IdPessoa));
CREATE TABLE Reserva (IdPessoa int(11) NOT NULL, IdReserva int(11) NOT NULL AUTO_INCREMENT, IdStatusReserva tinyint NOT NULL, DataRealizacaoReserva date NOT NULL, DataReserva date NOT NULL, DuracaoReserva smallint(6) NOT NULL, IdConta int(11) NOT NULL, PRIMARY KEY (IdReserva));
CREATE TABLE Pagamento (IdPagamento int(11) NOT NULL AUTO_INCREMENT, IdConta int(11) NOT NULL, DataVencimento date NOT NULL, ValorPagamento decimal(19, 0), DataPagamento date, PRIMARY KEY (IdPagamento));
CREATE TABLE PessoaJuridica (IdPessoa int(11) NOT NULL, cnpj varchar(20) NOT NULL, PRIMARY KEY (IdPessoa));
CREATE TABLE PessoaFisica (IdPessoa int(11) NOT NULL, cpf varchar(16) NOT NULL, PRIMARY KEY (IdPessoa));
CREATE TABLE Pessoa (IdPessoa int(11) NOT NULL AUTO_INCREMENT, Nome varchar(80) NOT NULL, Email varchar(250), PRIMARY KEY (IdPessoa));
CREATE TABLE TipoConta (IdTipoConta tinyint NOT NULL AUTO_INCREMENT, Descricao varchar(50) NOT NULL, PRIMARY KEY (IdTipoConta));
CREATE TABLE Conta (IdConta int(11) NOT NULL AUTO_INCREMENT, IdTipoConta tinyint NOT NULL, ValorConta decimal(19, 0) NOT NULL, IdPessoa int(11) NOT NULL, PRIMARY KEY (IdConta));
ALTER TABLE Cliente ADD INDEX FKCliente903170 (IdPessoa), ADD CONSTRAINT FKCliente903170 FOREIGN KEY (IdPessoa) REFERENCES Pessoa (IdPessoa);
ALTER TABLE Reserva ADD INDEX FKReserva321339 (IdPessoa), ADD CONSTRAINT FKReserva321339 FOREIGN KEY (IdPessoa) REFERENCES Cliente (IdPessoa);
ALTER TABLE ApartamentoReserva ADD INDEX FKApartament117883 (IdApartamento), ADD CONSTRAINT FKApartament117883 FOREIGN KEY (IdApartamento) REFERENCES Apartamento (IdApartamento);
ALTER TABLE ApartamentoReserva ADD INDEX FKApartament415166 (IdReserva), ADD CONSTRAINT FKApartament415166 FOREIGN KEY (IdReserva) REFERENCES Reserva (IdReserva);
ALTER TABLE Apartamento ADD INDEX FKApartament129965 (IdStatusApartamento), ADD CONSTRAINT FKApartament129965 FOREIGN KEY (IdStatusApartamento) REFERENCES StatusApartamento (IdStatusApartamento);
ALTER TABLE Reserva ADD INDEX FKReserva708692 (IdStatusReserva), ADD CONSTRAINT FKReserva708692 FOREIGN KEY (IdStatusReserva) REFERENCES StatusReserva (IdStatusReserva);
ALTER TABLE Reserva ADD INDEX FKReserva20483 (IdConta), ADD CONSTRAINT FKReserva20483 FOREIGN KEY (IdConta) REFERENCES Conta (IdConta);
ALTER TABLE Escala ADD INDEX FKEscala381325 (IdPessoa), ADD CONSTRAINT FKEscala381325 FOREIGN KEY (IdPessoa) REFERENCES Funcionario (IdPessoa);
ALTER TABLE Funcionario ADD INDEX FKFuncionari309962 (IdPapel), ADD CONSTRAINT FKFuncionari309962 FOREIGN KEY (IdPapel) REFERENCES Papel (IdPapel);
ALTER TABLE Conta ADD INDEX FKConta797230 (IdTipoConta), ADD CONSTRAINT FKConta797230 FOREIGN KEY (IdTipoConta) REFERENCES TipoConta (IdTipoConta);
ALTER TABLE PessoaFisica ADD INDEX FKPessoaFisi468164 (IdPessoa), ADD CONSTRAINT FKPessoaFisi468164 FOREIGN KEY (IdPessoa) REFERENCES Pessoa (IdPessoa);
ALTER TABLE PessoaJuridica ADD INDEX FKPessoaJuri427265 (IdPessoa), ADD CONSTRAINT FKPessoaJuri427265 FOREIGN KEY (IdPessoa) REFERENCES Pessoa (IdPessoa);
ALTER TABLE Conta ADD INDEX FKConta210490 (IdPessoa), ADD CONSTRAINT FKConta210490 FOREIGN KEY (IdPessoa) REFERENCES Cliente (IdPessoa);
ALTER TABLE Pagamento ADD INDEX FKPagamento108681 (IdConta), ADD CONSTRAINT FKPagamento108681 FOREIGN KEY (IdConta) REFERENCES Conta (IdConta);
ALTER TABLE Funcionario ADD INDEX FKFuncionari568939 (IdPessoa), ADD CONSTRAINT FKFuncionari568939 FOREIGN KEY (IdPessoa) REFERENCES PessoaFisica (IdPessoa);
ALTER TABLE Escala ADD INDEX FKEscala810085 (IdHorarioInicio), ADD CONSTRAINT FKEscala810085 FOREIGN KEY (IdHorarioInicio) REFERENCES Horario (IdHorario);
ALTER TABLE Escala ADD INDEX FKEscala701758 (IdHorarioFim), ADD CONSTRAINT FKEscala701758 FOREIGN KEY (IdHorarioFim) REFERENCES Horario (IdHorario);
